# version: '3'
name: sbg-ecom

services:
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1880:1880
    volumes:
      # Node-Red working files
      - ./tests/nodered/data:/data
      - ./tests/nodered/tests:/tests